### ISSUE TITLE
Examples on CIFAR

### ISSUE THREAD

**Issue by RiqiangGao** [ydwen/opensphere#2]
Very nice work! 
I wonder if it is possible to add examples on tiny datasets (e.g., MNIST, CIFAR) so people can easily run your code directly, without downloading large Face datasets?

**Comment by wy1iu** [comment]
Great suggestion. We currently focus on releasing the full version of the library, so right now we are out of bandwidth for this example. Hopefully we can come back to it later.

BTW, running our code on standard classification datasets should be simple, since training on face datasets is also essentially a classification task. You only need to slightly modify the dataloader (or atlerantively process the CIFAR data according to our dataloader).

**Comment by RiqiangGao** [comment]
Thank you! I will close this issue. 

I believe adding the tiny datasets would add more value to the library. Anyway, it is already awesome work.
